### ISSUE TITLE
Build failure with matrices 0.5.0

### ISSUE THREAD

**Issue by DanBurton** [kuribas/cubicbezier#9]
Build failure as seen on the Stackage build server:

```
Geom2D/CubicBezier/Numeric.hs:218:20: error:
    Not in scope: ‘G.unsafeTakeRow’
    Perhaps you meant ‘V.unsafeTake’ (imported from Data.Vector.Unboxed)
    Module ‘Data.Matrix.Generic’ does not export ‘unsafeTakeRow’.
    |
218 |                   (G.unsafeTakeRow m i)
    |                    ^^^^^^^^^^^^^^^
```

I was able to reproduce this locally like so:

```bash
stack unpack cubicbezier-0.6.0.5 && cd cubicbezier-0.6.0.5
edit stack.yaml # add the following stack.yaml
stack build --test --bench --no-run-benchmarks --fast
```

```yaml
# stack.yaml
resolver: nightly-2018-12-20
extra-deps:
- fast-math-1.0.2
- matrices-0.5.0
```
